version: "1.0"
stages:
  - "main_clone"
  - "build"
  - "install"
  - "test"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "PeterCharalambous/Cypress-Dashboard-Test"
    revision: "${{CF_BRANCH}}"
    stage: "main_clone"
  build:
    title: "Building Docker Image"
    type: "build"
    image_name: "cypresstest"
    working_directory: "${{main_clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
  install:
      image: "cypress/included:4.1.0"
      working_directory: "${{main_clone}}"
      description: "Installing dependencies..."
      commands:
          - "npm ci"
          - "npx cypress install"
          - "npx cypress cache path"
          - "npx cypress verify"
      paths:
        - "~/.cache"
        - "~/.npm"
      stage: "install"
  test:
    image: "node:latest"
    working_directory: "${{main_clone}}"
    description: "Performing tests..."
    commands:
        - "ls -a"
        - "npm test"
    stage: "test"